collage/frontend/registration.jsx

Made the Collage button w/o styling. Testing out a PR

COLLAGE-5 made the header button

---

collage/config.py
collage/model.py
requirements.txt

Add a scratch on the MySQL database connection.
We still need to set up these in `model.py`:
```Python
DB_HOST = ""
DB_USER = ""
DB_PASSWORD = ""
DB_DATABASE = ""
```

Add database connection; Add new package in requirements.txt

---

collage/frontend/About.js
collage/frontend/Home.js
collage/frontend/Mission.js
collage/frontend/Navbar.js
collage/frontend/Support.js
collage/frontend/registration.jsx
collage/templates/index.html
package-lock.json
package.json

Instead of using buttons for the navbar I changed it to use react-router-dom

COLLAGE-5 changed navbar using react-router-dom

---

LICENSE.txt
README.md
collage/server/auth.py
collage/server/main.py

We may need to discuss how to handle password hashing.
I left the function that checks input password and database password empty:
```Python
def correct_password(connection, password_in, password_db):
"""Return True when the user's actual password stored in database matched the user's input."""
return True
```
I also added a license for this repository:
https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en
Let me know what you think!

backend: Log in page email/password checking

---

README.md

- We don't need the license header
- We don't need some of the headings in the original table of contents

Edit Readme: delete license header and revise table of contents

---

collage/frontend/Login/Login-1.jsx
collage/frontend/Login/Wrapper.jsx
collage/frontend/Navbar.js
collage/frontend/Signup/Wrapper.jsx
collage/frontend/Styles/Signup.css
collage/frontend/registration.jsx
collage/frontend/styles/Navbar.css
webpack.config.js

Login feature: login page, background styling added for login in styles, revision of navbar

---

collage/frontend/Signup/Signup-1.jsx
collage/frontend/Signup/Signup-2.jsx
collage/frontend/Signup/Signup-3.jsx
collage/frontend/Signup/Signup-4.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/Styles/Signup.css
collage/frontend/main.jsx
package-lock.json
package.json

finished all signup pages and necessary buttons and inputs. Next steps will be to determine error checks and backend functionality

All sign up pages are created and connected

---

collage/__init__.py
collage/server/main.py
requirements.txt

Created the server functionality that **allows users to log in and log out** using their **Google account** using OAuth 2.0 protocol.

Finish login and logout (via Google OAuth 2.0) API functionalities

---

collage/config.py
collage/server/helper.py
collage/server/main.py
collage/server/recommend.py

This PR created a basic recommender system algorithm framework that sorts a list of classes based on user preferences.
We still need to implement the `users` SQL table to further refine the algorithm. More specifically, we still need to implement `get_user_info` in `helper.py`.

Collaborative filtering for course catalog endpoint

---

collage/server/main.py

Profile bar student info endpoint

---

collage/server/dalle.py
collage/server/main.py
collage/server/recommend.py
database/schema.sql
requirements.txt

- Finished writing access to OpenAI API 
- Refined `/api/catalog/` endpoint

`DALL-E` image generator backend; New Columns in `courses` table

---

collage/server/__init__.py
collage/server/dalle.py
collage/server/main.py

- Run the program and go to `http://127.0.0.1:8001/api/test/` to test if the JSON message is available

Fix API URL error: add init.py for `server` directory

---

.github/PULL_REQUEST_TEMPLATE.md

Please include a summary of the changes and/or the related issue below.
**Answer**: Create a universal template for all future PRs
For the following, type `x` in the square brackets to select an option, e.g. `- [x] Bug fix`

Add pull request template for future PRs

---

package-lock.json
package.json

Please include a summary of the changes and/or the related issue below.
**Answer**: Specify `node` version in `package.json`; update `package-lock.json`
For the following, type `x` in the square brackets to select an option, e.g. `- [x] Bug fix`

Specify `node` version in `package.json`; update `package-lock.json`

---

Procfile

Fix Procfile and configurations
**Answer**: replace with your response
For the following, type `x` in the square brackets to select an option, e.g. `- [x] Bug fix`

Fix Procfile and configurations

---

collage/config.py
collage/model.py

Please include a summary of the changes and/or the related issue below.
**Answer**: N/A
For the following, type `x` in the square brackets to select an option, e.g. `- [x] Bug fix`

Move database env variable to `.env`

---

collage/frontend/Auth.jsx
collage/frontend/Home/Home.jsx
collage/frontend/Landing/Landing.jsx
collage/frontend/Login/Wrapper.jsx
collage/frontend/Search/Wrapper.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/main.jsx
collage/frontend/registration.jsx

Added import lazy statement for registration.jsx, main.jsx, and landing.jsx

Imported lazy component

---

collage/server/agent.py
package-lock.json
package.json

Further optimize the AI Agent; try to add `--omit=dev` to solve Heroku memory issue

AI Agent Prompt Optimization; add `--omit=dev`

---

collage/server/nltk_utils.py

Omit nltk data downloading for Heroku

---

collage/server/agent.py
collage/server/course.py
database/schema.sql

Add backend functionality to render the individual course page. Later, we will need to add more functionality for the Collage Board and the AI Chatbot.

Backend Functionality for the Individual Course Page

---

collage/frontend/main.jsx
collage/frontend/registration.jsx

fixed loading issue with temporary loading text

---

collage/__init__.py
collage/model.py
collage/server/main.py
database/schema.sql
docs/agent.md

Revise `schema.sql`; update `agent`; set up database connection to remote `mysql` server

---

collage/frontend/Search/ProfileBar.jsx

Commented out data fetching for profile bar

Profile Bar error

---

collage/frontend/Navbar.jsx
collage/frontend/Search/Class-Card.jsx
collage/frontend/Search/SearchWrapper.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/main.jsx
collage/server/main.py

final updates

---

collage/frontend/Signup/Wrapper.jsx
collage/server/main.py

trying through process.env

---

collage/frontend/CSS/Search.css
collage/frontend/CSS/Signup.css
collage/frontend/CSS/Styles.module.css
collage/frontend/Landing/Landing-1.jsx
collage/frontend/Landing/Landing-4.jsx
collage/frontend/Login/Wrapper.jsx
collage/frontend/Search/SearchWrapper.jsx
collage/frontend/Signup/Interests-button.jsx
collage/frontend/Signup/Signup-3.jsx
collage/frontend/Signup/Signup-4.jsx
collage/frontend/Signup/Signup-5.jsx
collage/frontend/Signup/Wrapper.jsx
collage/server/main.py
collage/server/pastroutes.py
collage/templates/index.html
database/schema.sql

Ux updates

---

collage/frontend/CSS/Landing.css
collage/frontend/Landing/Landing-new.jsx

New Landing

---

collage/frontend/CSS/Landing.css
collage/frontend/Landing/Landing-new.jsx
collage/frontend/registration.jsx
package-lock.json
package.json
webpack.config.js

Redesigned landing page

---

collage/frontend/UserProfile/Personal.jsx

User Profile folder

---

collage/frontend/UserProfile/Personal.jsx

Unstyled Personal Box Component

---

collage/frontend/CoursePage/CoursePage.jsx
collage/frontend/RegistrationInfo/RegistrationInfo.jsx
collage/server/course_page.py
collage/server/user_profile.py

This PR contains all the **frontend and backend** code for the course page and registration info panel for the user profile.

Course Page and Registration Info for User Profile

---

collage/frontend/HomeWrapper.jsx
collage/frontend/Messages/MessagesWrapper.jsx
collage/frontend/Network/NetworkWrapper.jsx
collage/frontend/UserProfile/ProfileWrapper.jsx

updated onClick in navbar to render correct wrappers

---

collage/frontend/CoursePage/CoursePage.jsx
collage/server/course_page.py

Revised database queries for individual course page

Revised database queries for individual course page

---

collage/server/main.py
database/schema.sql

Connections APIs created - not tested

---

database/schema.sql

Revise `schema.sql` to match the latest database spec

Revise `schema.sql` to match the latest database spec

---

collage/frontend/CoursePage/CoursePage.jsx
collage/frontend/Dev.jsx
collage/server/agent.py
collage/server/course_page.py
collage/server/main.py
package-lock.json
package.json

Fix individual course page frontend

Fix individual course page frontend

---

collage/frontend/CSS/FileUpload.css
collage/frontend/CSS/Signup.css
collage/frontend/Class/Preview.jsx
collage/frontend/Class/rating.jsx
collage/frontend/Explore/Sidebar.jsx
collage/frontend/Signup/Interests-button.jsx
collage/frontend/Signup/Signup-3.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/UserProfile/FileUpload.jsx
collage/frontend/UserProfile/ProfileWrapper.jsx
collage/frontend/UserProfile/UserProfile.jsx
collage/server/main.py

added file uploading/management and minor api updates

---

collage/server/user_profile.py
database/schema.sql

Changes to db users schema and added personal info query to registration endpoint

---

collage/frontend/Class/Preview.jsx
collage/frontend/Explore/Catalog.jsx
collage/frontend/Explore/CourseTag.jsx
collage/server/main.py

connected catalog, search, individual course page

---

collage/server/main.py
database/schema.sql

Re-run scripts loading courses into db; revise `schema.sql`

Re-run scripts loading courses into db; revise `schema.sql`

---

collage/server/agent.py
collage/server/main.py
collage/server/nltk_utils.py
collage/server/recommend.py
requirements.txt

Modify `requirements.txt`; clear unncessary Python dependencies

---

package.json

Update `npm` version

---

package-lock.json

Revise `package-lock.json`

---

package.json

Add back `webpack`

---

package.json

Add `preinstall` script to `package.json`

---

collage/frontend/UserProfile/Savedcourses.jsx
collage/frontend/UserProfile/UserProfile.jsx

hide unsave button when not user

---

collage/frontend/CSS/ProfBar.css
collage/frontend/Class/ChatBox.jsx
collage/frontend/Class/Preview.jsx
collage/frontend/Explore/CourseTag.jsx
collage/frontend/Explore/Sidebar.jsx
collage/frontend/Network/Requests.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/UserProfile/Personal.jsx
collage/frontend/UserProfile/Savedcourses.jsx
collage/frontend/UserProfile/UserProfile.jsx
collage/frontend/main.jsx
collage/server/course_page.py
collage/server/main.py
collage/server/network.py
collage/server/user_profile.py

Sections include: chatbot UI, networking queries, user profile POST request, saved courses profile appearance, individual course page saving

Fixed a lot of bugs, read in description

---

collage/frontend/main.jsx

changed clientid

---

collage/frontend/Class/ChatBox.jsx
collage/frontend/Explore/CourseTag.jsx
collage/frontend/main.jsx
collage/server/main.py
collage/server/nlp.py
requirements.txt

Revise ratings and filters in course catalog; revise AI Advisor placeholder questions

Revise ratings and filters in course catalog; revise AI Advisor placeholder questions

---

requirements.txt

Revise `requirements.txt`

---

collage/server/nlp.py
requirements.txt

Remove LM Encoder to reduce bundle size

---

collage/server/main.py

Remove limit on number of courses in catalog page

---

collage/frontend/CSS/Personal.css
collage/frontend/CSS/loadScreen.css
collage/frontend/Class/ChatBox.jsx
collage/frontend/Class/IndividualCourse.jsx
collage/frontend/Class/SuggestedConnections.jsx
collage/frontend/Explore/Catalog.jsx
collage/frontend/Explore/Sidebar.jsx
collage/frontend/HomeWrapper.jsx
collage/frontend/Landing/Landing-new.jsx
collage/frontend/Network/Connect.jsx
collage/frontend/UserProfile/Personal.jsx
collage/frontend/loading/LoadScreen.jsx
collage/frontend/registration.jsx
collage/server/course_page.py

Added in loading screen, fixed The Collage Board, adding some other styling, changed following/followers to connections

---

collage/frontend/Class/SuggestedConnections.jsx

changed suggested connections

---

collage/frontend/Class/SuggestedConnections.jsx

suggested conn change

---

collage/frontend/CSS/classPreview.css
collage/frontend/Class/Preview.jsx
collage/frontend/Explore/Sidebar.jsx
collage/frontend/UserProfile/Personal.jsx
collage/frontend/main.jsx
collage/server/user_profile.py

updated user-profile and class preview

---

collage/frontend/CSS/Landing.css
collage/frontend/CSS/Personal.css
collage/frontend/Landing/Landing-new.jsx
collage/frontend/UserProfile/Personal.jsx

fixed link issue and added help form to landing page

---

collage/frontend/CSS/Landing.css
collage/frontend/Landing/Landing-new.jsx

Made landing page responsive for mobile

---

collage/frontend/Landing/Landing-new.jsx
collage/frontend/Signup/Signup-4.jsx
collage/frontend/UserProfile/UserProfile.jsx
collage/frontend/main.jsx
collage/frontend/registration.jsx

Temporarily shut down transcript/resume drop

---

collage/frontend/CSS/Signup.css
collage/frontend/Login/Wrapper.jsx
collage/frontend/Signup/Signup-4.jsx
collage/frontend/Signup/Wrapper.jsx
collage/frontend/UserProfile/FileUpload.jsx
collage/frontend/UserProfile/Personal.jsx
collage/frontend/UserProfile/UserProfile.jsx
collage/frontend/main.jsx
collage/model.py
collage/server/main.py
database/schema.sql
package-lock.json
package.json
webpack.config.js

fixed firebase auth issues

---

collage/frontend/Signup/Wrapper.jsx
collage/server/agent.py
collage/server/course_page.py
collage/server/main.py
database/schema.sql

Add `resume_keywords` to AI Chatbot and Recommender

Add `resume_keywords` to AI Chatbot and Recommender

---

collage/frontend/Explore/Sidebar.jsx

fixed sidebar date issue

---

collage/frontend/UserProfile/FileUpload.jsx
collage/frontend/UserProfile/Schedule.jsx
collage/frontend/UserProfile/UserProfile.jsx

Added schedule upload feature

---

collage/frontend/UserProfile/FileUpload.jsx
collage/frontend/UserProfile/Schedule.jsx
collage/frontend/UserProfile/UserProfile.jsx
collage/server/user_profile.py

Added in feature to view connections' schedules
